name: pose
description: Library for viewing, augmenting, and handling .pose files
version: 1.0.0
repository: https://github.com/bipin/pose
topics:
  - pose

environment:
  sdk: ^3.0.0

dependencies:
  # 

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0